### ISSUE TITLE
element-ui 里面icon都没有被替换，有什么解决方案吗

### ISSUE THREAD

**Issue by polmqwaz** [JimFirst/change-prefix-loader#1]
![image](https://user-images.githubusercontent.com/27537320/163676431-c47bb794-93ef-4592-ac5a-3e29dd9d6d57.png)

**Comment by polmqwaz** [comment]
可以了，正则表达式里面有(?!icon)，请问为什么要打这个专门屏蔽掉，是有什么原因吗

**Comment by JimFirst** [comment]
> 可以了，正则表达式里面有(?!icon)，请问为什么要打这个专门屏蔽掉，是有什么原因吗

icon是字体库引入的，所以不能被替换，替换了会找不到字体库
