### ISSUE TITLE
组件的前缀也被修改了怎么半？

### ISSUE THREAD

**Issue by Sonirjodxpro** [JimFirst/change-prefix-loader#2]
![image](https://user-images.githubusercontent.com/37522640/176579996-630575a8-9dcc-49fb-af09-ecaf15f8fdd5.png)
el-checkbox 变成了child-checkbox

**Comment by JimFirst** [comment]
这个插件就是用来修改组件的前缀的，样式前缀需要另外一个loader，[postcss-change-css-prefix](https://github.com/JimFirst/postcss-change-css-prefix)
