### ISSUE TITLE
请问element-plus怎么修改呢？

### ISSUE THREAD

**Issue by erin20188** [JimFirst/change-prefix-loader#5]
配置如下，没有生效
`chainWebpack: config => {
    config.module
      .rule('change-prefix')
      .test(/\.js$/)
      .include.add(path.resolve(__dirname, './node_modules/element-plus/lib'))
      .end()
      .use('change-prefix')
      .loader('change-prefix-loader')
      .options({
        prefix: 'el-',
        replace: 'qb-'
      })
      .end()
  }`

**Comment by JimFirst** [comment]
> 配置如下，没有生效 `chainWebpack: config => { config.module .rule('change-prefix') .test(/\.js$/) .include.add(path.resolve(__dirname, './node_modules/element-plus/lib')) .end() .use('change-prefix') .loader('change-prefix-loader') .options({ prefix: 'el-', replace: 'qb-' }) .end() }`

1.首先，提issue之前，先翻一下closed的有没有相似或者一样的问题
2.请认真读一下我的文档和element-plus官方文档，element-plus支持namespace，不需要额外的方法
