### ISSUE TITLE
"When modifying element-plus, it didn't work."

### ISSUE THREAD

**Issue by Yosin527** [JimFirst/change-prefix-loader#7]

**Comment by JimFirst** [comment]
it only support element-ui，and the element-plus official has supported change prefix



---Original---
From: ***@***.***&gt;
Date: Sat, Apr 1, 2023 16:18 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [JimFirst/change-prefix-loader] "When modifying element-plus, itdidn't work." (Issue #7)

**Comment by Yosin527** [comment]
> it only support element-ui，and the element-plus official has supported change prefix
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sat, Apr 1, 2023 16:18 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [JimFirst/change-prefix-loader] "When modifying element-plus, itdidn't work." (Issue #7) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

ok,thanks
